### PR TITLE
Sa/create header image

### LINKED ISSUE #2: Create the Header Image
**Context**
We need a header to capture the user's attention. 

**Problem**
We don't have one...yet.

**Acceptance Criteria:**
* The appearance of this component's desktop version must be exact or (very) similar to the approved [Figma Mock-up](https://www.figma.com/file/ciTL29R7gAaKkipH6v8QLL/Technolgap-official-Mockups?node-id=483%3A0)
* Put text on top of the header based on [Figma Mock-up](https://www.figma.com/file/ciTL29R7gAaKkipH6v8QLL/Technolgap-official-Mockups?node-id=483%3A0)
* Must be mobile-friendly 

Screen Shot 2020-08-23 at 8 39 44 AM

### PR DESCRIPTION
**Pull request by safa-howaid**
Header is all done! I also added some media queries to adjust it based on screen size.

Here's how it looks like on desktop vs mobile: 

Screen Shot 2020-09-20 at 7 29 26 PM
Screen Shot 2020-09-20 at 7 32 15 PM

Mobile may need a bit of adjustment to account for the navigation hamburger!

Closes #2

### CODE REVIEW

**Comment by safa-howaid** [comment]
Nvm, I added a top margin to fix that! 😅 
Screen Shot 2020-09-20 at 7 42 07 PM

**Comment by Monica-Vu** [comment]
You matched the banner's width and height to the Figma mockups, which is great. I think if you can, can you try to match the width to the navigation bar. I also think a bit more white space would be nice! Thank you. 

Screen Shot 2020-09-21 at 11 05 10 PM

**Comment by Monica-Vu** [comment]
Did you by chance forget to push your changes to the Github? This is what if my screen has a smaller width:
Screen Shot 2020-09-21 at 11 08 32 PM

**Comment by safa-howaid** [comment]
Thanks for the feedback! I was able to push the margins in a bit more to match the navigation bar and this is what it look like now:
Screen Shot 2020-09-22 at 4 30 19 PM

However, one thing I noticed after matching the width of the navigation bar is that the left margin is 20px more than the right margin, which makes the header looks like it's pushed to the right, is there a way to fix it?

**Comment by Monica-Vu** [comment]
> Thanks for the feedback! I was able to push the margins in a bit more to match the navigation bar and this is what it looks like now:
> Screen Shot 2020-09-22 at 4 37 56 PM
> 
> However, one thing I noticed after matching the width of the navigation bar is that the left margin is 20px more than the right margin, which makes the header looks like it's pushed to the right, is there a way to fix it?

Good catch! Hmmm...I looked at it and personally I don't think to notice a huge difference and it doesn't really have a big impact so I would say it's good to go and we can always do adjustments later, especially for minor ones like this :)

**Review by Monica-Vu — APPROVED** [review]

**Pull request merged**
