### PR TITLE
Create Responsive Navigation Bar

### PR DESCRIPTION
**Pull request by Jo-Sundaram**
### What is the feature?

- navigation bar at the top of the website, responsive to smaller screen size for mobile
- includes technolgap + technol-leaf logo
- links to each page of the website with an active page indicatior

### What is the solution?
- Create navbar component that uses a custom ActiveLink component for each page link
- use media query to change the horizontal navbar to a vertical side navbar for mobile screen

#### My work:
/Navbar/NavBar.js
/Navbar/ActiveLink.js
/Navbar/NavBar.module.scss

### Here are some images to demonstrate the ActiveLink component. The 'contact' and 'discover' pages were just for demonstration and are not actually included in my branch. 

image
image
image
image

<hr>

### Here's a gif to demonstrate the responsive/mobile navbar. 

responsive-navbar

### Next Steps:

I would like to integrate this with the master branch to make sure it functions properly with the rest of the content.

### CODE REVIEW

**Comment by Monica-Vu** [comment]
Can you push your latest changes to your branch (`JS/create-navbar`)? Just want to check out it :D 
What does it look like mobile version?

**Comment by Jo-Sundaram** [comment]
> Can you push your latest changes to your branch (`JS/create-navbar`)? Just want to check out it :D
> What does it look like mobile version?

Just pushed! Sorry about that, I forgot to add the untracked files.
I've yet to make the scaling mobile-friendly but I will be working on that as well.

**Comment by Jo-Sundaram** [comment]
I made the navbar more mobile friendly and updated my pull request.

**Comment by Monica-Vu** [comment]
You should be merging your branch into master (don't worry, it's kind of confusing 😅): you can make a new PR or I think edit this one. It should be like this:
Screen Shot 2020-09-03 at 7 50 47 PM

I was confused to why I couldn't see what your changes would be 😆

My current feedback is to change the colour of the hamburger to `raisin-dark` to be more consistent with the color theme. 

Otherwise, I checked out your branch and it looked good. I'm going to verify with @alexaliaskovski about her opinion with the mobile version.

**Comment by Jo-Sundaram** [comment]
Yeah I'm also not too sure about the colour scheme haha. 
> Change the navigation menu's width to 100%
I believe in our Figma mockups we had a margin all around the page so I left it with a margin. If Alexa's ok with having 100% then I'll be sure to change it.  But if it looks good otherwise I'm going to go ahead and merge.

**Comment by alexaliaskovski** [comment]
I know this PR has already merged but some comments on the design of the mobile nav bar (you can perhaps follow up in another pr?)

- love the idea of a hamburger menu!! I think it intuitively makes more sense to have coming out of the left side rather than the right? what made you choose the right over the left?
- can we make the menu come out further across the page (maybe ~75% of the way across), have the background of them menu slightly transparent (so we can kinda see what's on the page), and have all the menu items (home, about us) stacked together more tightly at the top?

Great work, keep it up! So exciting to see it all come together!!

**Comment by Jo-Sundaram** [comment]
> what made you choose the right over the left?

Putting it on the top right was what first came to mind when thinking of mobile apps. However, looking at other mobile apps some seem to have their menu on the top right (Instagram settings menu) and some on the top left (Reddit). I can definitely move it to the left side no problem. 

How do you feel about the colours and margin? I took Monica's advice and changed the mobile menu colour to white. 
Should I change the web version to have 100% width or leave it with the current margin? 
I'll post a follow-up PR with these adjustments made!

**Pull request merged**
